### ISSUE TITLE
Some characters cause erroneous output

### ISSUE THREAD

**Issue by Bersam** [aaronjensen/eslintd-fix#13]
It seems eslintd-fix get confused when we split window to two windows and replace one window errors with the other errors.

**Comment by aaronjensen** [comment]
Hi @Bersam, thank you for reporting this. Could you give me some specific reproduction steps, I'm not sure that I quite understand the scenario you're describing.

**Comment by Bersam** [comment]
@aaronjensen Hey Aaron, If you take a look at these pictures, you get the whole idea. I split window in two (in this case it's the same file.) and after that, I just change something, (or sometime paste something) and save it. as you can see, it will act as it's parsing another file on this one or maybe get window content instead of pane content (as it is splitted)
I've checked eslintd from terminal and it did the job without any problem.

before:
![before](https://user-images.githubusercontent.com/497148/51801954-d0adde00-2259-11e9-901c-c1d5995b41c6.png)

after:
![after](https://user-images.githubusercontent.com/497148/51801953-d0adde00-2259-11e9-8d7b-1f9165d8d9a8.png)

**Comment by Bersam** [comment]
@aaronjensen I found out that the problem is when I have non ascii characters in my code (in this case, Persian) and it's not related to window or pane. But the thing is that eslint_d on the same file from command line works without any problem.

to reproduce, you can use this simple block of code:
```javascript
import React from 'react';
import Link from 'next/link';
import Layout from '../components/layout';
import TopHeader from '../components/topheader';
const Product = () => (
  <Layout>
    <TopHeader
      background="/static/images/header/product.png"
    >
      <h1 className="pull-left text-left">فروشگاه<br />محصولات</h1>
    </TopHeader>
  </Layout>
);

export default Product;
```

**Comment by aaronjensen** [comment]
Thank you for the detail... unfortunately, I'm not able to reproduce it. 

Can you check the value of `buffer-file-coding-system`? Mine is `utf-8-unix`.

Also, could you paste the result of `emacs-version`?

**Comment by aaronjensen** [comment]
Oh, and what version of `eslint_d` do you have installed?

**Comment by omidmnz** [comment]
I have the same problem with `eslint_d v5.12.1 (eslint_d v7.2.0)`, `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05`. The buffer encoding is `unix`.
I found out one more thing: the bug doesn't exist with the default `eslint` config.
Here is the eslintrc from the project that I can reproduce the bug in:
```json
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "browser": true,
    "amd": true,
    "es6": true,
    "node": true,
    "mocha": true
  },
  "extends": [
    "airbnb",
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "rules": {
    "semi": [2, "always"],
    "quotes": [1, "single"],
    "no-undef": 1,
    "no-extra-semi": 1,
    "no-console": 1,
    "no-unused-vars": 1,
    "no-trailing-spaces": [1, { "skipBlankLines": true }],
    "no-unreachable": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/jsx-filename-extension": 0,
    "react/prop-types": 0, // Disabled by this issue https://github.com/acdlite/recompose/issues/150
    "import/no-unresolved": [0, { "commonjs": true, "amd": true }],
    "import/named": 1,
    "import/namespace": 1,
    "import/default": 1,
    "import/export": 1,
    "import/no-extraneous-dependencies": 0,
    "import/extensions": 0
  }
}
```

**Comment by aaronjensen** [comment]
@omidmnz Can you try reencoding your file as utf-8 and see if it still happens? `C-x C-m f`

**Comment by aaronjensen** [comment]
Also, if one of you could provide a minimal reproduction project, that would help a lot.

**Comment by aaronjensen** [comment]
I tried to create a repro here, but I am not able to reproduce it: https://github.com/aaronjensen/eslintd-repro

**Comment by omidmnz** [comment]
I can reproduce it in your repo! I just opened `test.js` and issued `M-x eslintd-fix`.

**Comment by aaronjensen** [comment]
@omidmnz Interesting. I'm on Emacs 27, let me try on Emacs 26. In the meantime, can you take a screenshot of the result you're seeing?

**Comment by aaronjensen** [comment]
Okay, I can reproduce it with Emacs 26.1, but not in 27. I'm guessing this is a bug they fixed along the way. If you can upgrade to 27, I'd recommend it. It's worked fine for me for a while now. Otherwise, I'll see if I can track down the commit that fixed it.

**Comment by aaronjensen** [comment]
I just tested on the emacs-26 branch (the 26.2 pre-release) and it worked there, so the fix should be coming soon in Emacs 26.2.

**Comment by omidmnz** [comment]
Thank you. I just compiled Emacs 27. I think it'll do the job until the next version is released.

**Comment by Bersam** [comment]
@aaronjensen @omidmnz thank you both, I have  Emacs 27 now and I don't have this problem anymore. I close this issue as it's not related directly to eslintd-fix.

**Comment by aaronjensen** [comment]
No problem at all, thank you both for your help reproducing it.
