### ISSUE TITLE
Permit customization of timeout duration

### ISSUE THREAD

**Issue by harto** [aaronjensen/eslintd-fix#17]
I work on a largeish TypeScript project, and in some cases files take a few seconds to be fixed with `eslintd-fix`.

I noticed that for such files, if the timeout in `eslintd-fix--wait-for-connection-to-close` is exceeded, `eslintd-fix` will give up and the files are not fixed. In that case I have to resort to running `eslint_d --fix …` at the command line.

Fixing the project's eslint configuration would be preferable 🙂 but in the meantime, it would be useful if the timeout was customizable.

**Comment by aaronjensen** [comment]
It looks like it's currently around 2 seconds (200 * 0.01s) 

Is that what you're seeing, that it takes over 2s? Just want to confirm the order of magnitude.

**Comment by aaronjensen** [comment]
Added in https://github.com/aaronjensen/eslintd-fix/commit/5f9daecd4a02418515070b8084cb06e2251e2119 

Please let me know if that works for you. You can customize `eslintd-fix-timeout-seconds`

**Comment by harto** [comment]
> It looks like it's currently around 2 seconds (200 * 0.01s)
> 
> Is that what you're seeing, that it takes over 2s? Just want to confirm the order of magnitude.

Yes, that's right :)

**Comment by harto** [comment]
Thank you!
