### ISSUE TITLE
eslintd-fix has started to not work reliably recently

### ISSUE THREAD

**Issue by DamienCassou** [aaronjensen/eslintd-fix#18]
I don't know exactly what happens nor if this is eslintd-fix fault so take this issue with a grain of salt. It seems that, very often, eslintd-fix won't fix my buffer: nothing happens and I don't have any error message. Killing the Emacs process and the system process don't fix the issue.

**Comment by aaronjensen** [comment]
Hi @DamienCassou, one unfortunate thing is that `eslintd-fix` doesn't do a good job showing errors when they happen. I've found that when I see the behavior you're describing there's usually an issue with my eslint setup. Sometimes, restarting `eslint_d` helps. Sometimes it's an issue with plugins not being installed globally, but using a globally installed `eslint_d`. Other times, it's about the config not resolving correctly, which you can check with `eslint_d --print-config <path to file>`.

I also had a frustrating issue where I switched to using `@babel/eslint-parser` and the way that it finds your babel config did not work with eslint_d, so I had to hard code the location of my babel config:

```
  parserOptions: {
    babelOptions: { configFile: require.resolve("./babel.config.json") },
  },
```

Hopefully some of that helps. In any case, I really need to add error handling. The prettier package does a good job of that.

**Comment by DamienCassou** [comment]
Thank you for your answer! I will use it when/if the problem happens again.

**Comment by DamienCassou** [comment]
@aaronjensen I switched to `@babel/eslint-parser` and nothing works anymore (and I had problems even before).

I used your `parserOptions.babelOptions` trick above:

```js
{
	parser: "@babel/eslint-parser",
	parserOptions: {
		sourceType: "module",
		babelOptions: { configFile: require.resolve("./babel.config.js") },
	}
	...
}
```

 and here is some log:

```
$ eslint_d status
Not running
$ eslint_d start
Running. No instances cached.
$ eslint_d --print-config ~/project/js/core/widgets/StackEditorWidget.js 
$ eslint_d status
Not running
```

As you can see, `eslint_d --print-config` prints nothing at all and kills `eslint_d` server. 

I get a correct configuration when using `eslint --print-config`.

```
$ ~/project/node_modules/.bin/eslint --print-config ~/project/js/core/widgets/StackEditorWidget.js | grep --after-context=4 parser
  "parser": "~/project/node_modules/@babel/eslint-parser/lib/index.js",
  "parserOptions": {
    "sourceType": "module",
    "babelOptions": {
      "configFile": "~/project/babel.config.js"
    }
```

> Sometimes it's an issue with plugins not being installed globally, but using a globally installed eslint_d.

Maybe that's my problem because
1. I have a globally installed eslint_d; and
2. I'm using a few eslint plugins (e.g., `eslint-plugin-prettier`) and even the `@babel/eslint-parser` in my project.

I think I remember seeing some documentation about that setup but can't find it anywhere anymore.

What is the correct setup please?

```
$ eslint_d --version
v7.8.1 (eslint_d v10.0.4)
```

Thank you.

**Comment by aaronjensen** [comment]
Hi @DamienCassou I've never had luck w/ installing `eslint_d` globally. I tend to put it in each project, which keeps it working. You might try installing all of your plugins globally and see if that helps if you can't do that.

I really need to do a better job of showing errors... but I don't really even use this package anymore as the only reason I used it was prettier and https://github.com/jscheid/prettier.el is even faster, so I doubt I'll get around to it...

**Comment by DamienCassou** [comment]
Thank you for your quick answer. What does a per-project configuration look like;

- is `eslint_d` part of your package.json even though it's not a dependency and not all the team might use it?
- do you pass `eslint_d` special options so you can have one instance per project without having each one erasing `~/.eslint_d`?
- I guess you set `eslintd-fix-executable` as a directory-local variable but which value do you give it?

>  I don't really even use this package anymore

I see. Would you still review PRs?

**Comment by aaronjensen** [comment]
> * is `eslint_d` part of your package.json even though it's not a dependency and not all the team might use it?

Yes

> * do you pass `eslint_d` special options so you can have one instance per project without having each one erasing `~/.eslint_d`

I don't use `~/.eslint_d`, what do you use that for?

> I guess you set eslintd-fix-executable as a directory-local variable but which value do you give it?

Yes. I use this:

```el
(use-package eslintd-fix
  :hook (((typescript-web-mode js-web-mode) . aj/set-eslint-executable))

  :preface
  (defun aj/locate-npm-executable (name)
    (when buffer-file-name
      (let* ((node-module-path (concat "node_modules/.bin/" name))
             (dir (locate-dominating-file buffer-file-name node-module-path)))
        (if dir
            (concat dir node-module-path)
          (executable-find name)))))

  (defun aj/set-eslint-executable ()
    (interactive)
    (when-let* ((executable (aj/locate-npm-executable "eslint_d")))
      (setq-local eslintd-fix-executable executable)
      (setq-local flycheck-javascript-eslint-executable executable)))

  (defun aj/enable-eslintd-fix ()
    "Enable eslintd-fix if we're not in node_modules"
    (when (and buffer-file-name
               (not (string-match "\\/node_modules\\/" buffer-file-name)))
      (eslintd-fix-mode))))
```

**Comment by DamienCassou** [comment]
> I don't use ~/.eslint_d, what do you use that for?

I guess you just forgot :smile: : `~/.eslint_d` is the default value of `eslintd-fix-portfile`. It's a file generated by eslint_d.js to store its port and token so that clients can connect to it.

Thank you very much for your code. From what I understand, what you did only works if you have one eslint-based project you want to work on at a time. This is because as soon as one eslind_d.js instance is running from a project's directory, you can't start a new one from another directory: eslint_d will just reuse the existing server by connecting to it after reading `~/.eslint_d`.

**Comment by aaronjensen** [comment]
Ah, yea, sorry it's been a while.

What you're describing isn't true in my experience. It works fine across multiple projects as that's how eslint_d is designed to work. There's only one instance of the server, but multiple instances of the client. I have no idea if or why that makes a difference but it seems to for me. What I know is that I used the above configuration across multiple projects simultaneously for a long time and it worked.

Oh, and yes, I'd still review pull requests.

Thanks!

**Comment by DamienCassou** [comment]
Aaron Jensen ***@***.***> writes:
> Ah, yea, sorry it's been a while.


nothing to be sorry about!


> What you're describing isn't true in my experience. It works fine
> across multiple projects as that's how eslint_d is designed to
> work. There's only one instance of the server, but multiple instances
> of the client. I have no idea if or why that makes a difference but it
> seems to for me. What I know is that I used the above configuration
> across multiple projects simultaneously for a long time and it worked.


awesome. Thank you!

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
I'm closing the ticket. It seems the issue hasn't reappeared for some time now.
