### ISSUE TITLE
Time for a release ?

### ISSUE THREAD

**Issue by DamienCassou** [aaronjensen/eslintd-fix#2]
Hi,

I've enjoyed your package for some days now and I love it. Would you mind adding a git tag to a commit so that melpa stable can provide a stable version?

Thanks

**Comment by aaronjensen** [comment]
Thank you for the kind words. I've tagged v1.0.0 and pushed it. It's my first time releasing to melpa stable, so if that's all I need to do then it should pick it up. If there's more I need to do or you don't see it later today, please let me know by reopening. Thanks!
