### ISSUE TITLE
Running from a project subdirectory causes errors

### ISSUE THREAD

**Issue by fixmaker** [aaronjensen/eslintd-fix#21]
I am using `@babel/eslint-parser` in my project's `.eslintrc.json`. Imagine a simple project structure such as this:

```
my_project
 |-- package.json
 |-- .eslintrc.json
 |-- babel.config.json
 |-- node_modules
 \-- src
      \-- subdir
          \-- code.js
```

If I run the following (via the command line) from the `my_project` directory then everything works as expected:
```
eslint_d src/subdir/code.js
```
However, if I change to the `subdir` directory and try
```
eslint_d code.js
```
...then I get errors about `No Babel config file detected for my_project/src/subdir/code.js`.

It seems the parser cannot find the config file when it's in a different directory to where eslint_d is run. This causes `(eslintd-fix)` to fail (usually silently, which is confusing). This problem could be avoided if eslintd-fix was to run the eslint_d executable from the project root, rather than the same directory as the file that the current buffer is visiting.

As a side note, I also use flycheck to do the actual linting and this has no problem. I think the reason for that is that flycheck will actually try and determine the project's root directory automatically.

Is there an easy way to get eslintd-fix to run `eslint_d` from the project root directory? I've tried looking at the code but my emacs-fu isn't up to it at the moment.

**Comment by aaronjensen** [comment]
What you are describing is not what I see. `eslintd-fix` only runs `eslint_d` once, to start the server and it is irrelevant where it is run from though you should have `eslintd-fix-executable` set correctly. After that, it sends commands over a socket that necessarily have the full path

You may want to try putting `root: true` in your eslint config and see if that helps. Also, you may need to set your babel options explicitly. I have this in my config and I don't recall why (it may have been related to this):

```
module.exports = {
  root: true,
  parserOptions: {
    babelOptions: { configFile: require.resolve("./babel.config.json") },
  },
}
```

Ultimately, the error you get when running `eslint_d` is the problem, eslintd-fix is doing the right thing.

Though it'd be great if it showed you the error....

**Comment by aaronjensen** [comment]
I'm going to close this out for now, but please let me know if you run into any other issues.

Thanks!
