### ISSUE TITLE
Fail w/ vague error message if Emacs started from Fish Shell

### ISSUE THREAD

**Issue by orther** [aaronjensen/eslintd-fix#4]
## Problems w/ Fish Shell
I recently started opening emacs from my terminal (which I use [Fish Shell](https://fishshell.com)) and `eslintd-fix` stopped working. I finally tracked down the issue being due to the fact that the shell commands this package calls are not supported by Fish's syntax.

I'm opening this issue because the error message returned in this case lead me to believe there was an issue with my `eslint_d` installation or path. Here is the error message it currently returns:
```eslintd-fix: Could not find eslint_d or it does not have the ‘--fix-to-stdout’ feature.```

## Where things fail w/ Fish Shell
Since `eslintd-fix--compatible-versionp` doesn't handle an exit status code of `123` (this is the status code returned from Fish shell) any different than `1` (status code grep return when no matches found) the error message will always be the same. 

For reference here is the output from the shell command used by `eslintd-fix--compatible-versionp` when I open emacs from w/ env var `$SHELL` pointing to fish:
```fish: Unknown command '(/usr/local/bin/eslint_d --help | grep -qe '--fix-to-stdout')'```

## Closing
I'm not sure whether it makes sense to update this package to support fish shell completely or update it to provide more details to help indicate what is causing the failure. I figured I would open an issue and you can decide if anything should be done. Even if nothing is changed, this issue could be a useful reference for anyone else running into this issue.

**Comment by aaronjensen** [comment]
Hi @orther, thank you for the report, I appreciate it.

I'd be curious what other packages do. I'd probably rather not attempt fish unless the way to support it was to somehow rely less on shell constructs entirely (like piping). In this particular case, I could do something like `shell-command-to-string` and search for it in emacs, however that would only solve this issue. I currently rely on a few things that fish may not like to actually do the linting.

I'd certainly support either a detection of a shell other than bash/zsh and warning about that, or just adding to the warning message that you may have an unsupported shell.

**Comment by orther** [comment]
Yeah it seems like most people avoid using the fish shell within emacs so warning about the non-zsh|bash shell when shell command fails seems adequate to me. If the verify command fails with exit status other than `1` another error message could be shown that mentions the shell. Beyond that testing `shell-file-name` variable could allow for more specific error message suggestions. For example if `fish` shell is detected it can warn about that. If you like I can throw a pull request together for this.

## Fix for Emacs opened from Fish Shell
For reference, to make eslintd-fix work when I open emacs from fish shell (or any shell other than bash for that matter) I set bash as the shell to use for called shell commands by adding the following to my `~/.emacs.d/init.el`:
```elisp
(setq shell-file-name "/bin/bash")
```

**Comment by orther** [comment]
I'm not aware if there is an idiomatic emacs way to detect the shell but came across this issue fish-shell/fish-shell#374 that provided a nice solution.  I am leaving it here if you did want to add warning(s) about non-bash/zsh shells but didn't already have a good strategy for to detect which shell. 

Basically Bash sets the internal variable (not exported) `$BASH_VERSION`. Since it is not passed down to subprocesses checking if it has a value set is a simple way to detect if the current shell is indeed Bash. Zsh has `$ZSH_VERSION` and fish did the same w/ `$FISH_VERSION`.

I added a little check in my init files to protect myself in the future similar to this:
```elisp
(or
 (zerop (call-process-shell-command "test $BASH_VERSION"))
 (zerop (call-process-shell-command "test $ZSH_VERSION")))
```

**Comment by sebastiencs** [comment]
@orther I just see your issue after making https://github.com/aaronjensen/eslintd-fix/pull/11, this should fixes your case

**Comment by aaronjensen** [comment]
Fixed in #11, thank you @sebastiencs. Please feel free to reopen or open a new issue if there are still problems with Fish.

**Comment by orther** [comment]
Thanks @sebastiencs and @aaronjensen works for me!

**Comment by sebastiencs** [comment]
You're welcome :) I don't have any other issue so far
