### ISSUE TITLE
Adding restart/stop functionality?

### ISSUE THREAD

**Issue by orther** [aaronjensen/eslintd-fix#5]
I did not realize for months that eslint_d.js does not take in any changes to .eslintrc files make if it is running. I wasted a decent amount of time before realizing that was the case and have been trying to think of solutions. I thought the bare minimum could be adding a function that would restart or stop the current eslint_d server. With those facilities in place I figured a more advanced automated process could be figured out so make sure people don't waste their time on old config settings showing errors that are not fixed because eslint_d doesn't pickup changes.

Have you considered or would you consider adding functions to do `eslint_d restart` and/or `eslint_d stop`? If yes (or even no I guess 😄 ) Do you have an idea to gracefully solve this problem?

**Comment by aaronjensen** [comment]
Hey @orther, I'm not sure how I would solve that here... it seems it would be best solved in eslint_d via some sort of file system watching, or one could solve it on their machine w/ a similar mechanism.

If you want to do it from emacs, you could do something like: 

```elisp
(defun eslintd-restart ()
  (interactive)
  (call-process (executable-find eslintd-fix-executable) nil nil nil "restart"))
```

You could even add an `after-save-hook` to restart it if you're saving an eslint config. Of course, that would fail if it was updated by git...

**Comment by orther** [comment]
Thanks @aaronjensen I was thinking along the same lines about needing to fix it from within eslint_d. Going to throw that snippet in my personal config for the time being (so I'm closing the issue). Thanks!
