### ISSUE TITLE
Better check buffer size before call eslint_d 

### ISSUE THREAD

**Issue by yqrashawn** [aaronjensen/eslintd-fix#6]
Say, don't fix large buffer in emacs. It's really slow. Better call eslint_d in shell.

**Comment by aaronjensen** [comment]
Hi @yqrashawn,

How large is the buffer? How slow is slow? It would certainly be possible for you to advise `eslintd-fix` to first check buffer size and do nothing for larger buffers. I don't think I will build that in, however, as deciding whether or not to enable it is a separate concern from what this package does.

I would be happy to accept an update to the readme with instructions on how to do it, however.

Thanks!

**Comment by aaronjensen** [comment]
Closing for now, if someone wants to contribute what was mentioned above or provide an example with more details I'd appreciate it. Thanks!
