### ISSUE TITLE
Could not start or connect to eslint_d.

### ISSUE THREAD

**Issue by psamim** [aaronjensen/eslintd-fix#8]
Hi,

I just updated and found this error `Could not start or connect to eslint_d.`.

Using Spacemacs, development branch on Emacs 2.3, Archlinux. Installed `eslint_d` from melpa.

**Comment by zphr** [comment]
Can confirm. Used to work on MacOS 10.12.6, Emacs 25.1.1 but after the update it does not anymore :(. 

BTW thanks for this great package @aaronjensen , it keeps me sane!

**Comment by aaronjensen** [comment]
Doh, I'm sorry about that. I recently more or less rewrote the package so I'm not surprised there were some issues.

That said, I'm not sure what is wrong and the current version is slightly different and does not have that message anymore (that message was only there for a day or so). Could you please try updating again? Also, make sure that your `eslint_d` is up to date.

If, after updating both, you still see that error message I'll happily help debug.

**Comment by psamim** [comment]
Thanks! Surely I will help debug. I updated both `eslint_d` from npm and `eslintd-fix` from melpa. Now `eslint_d` is at `v4.12.0 (eslint_d v5.2.0)` and `describe-package` for `eslintd-fix` says:

```
eslintd-fix is an installed package.

     Status: Installed in ‘eslintd-fix-20171125.1432/’ (unsigned). Delete
    Version: 20171125.1432
    Summary: use eslint_d to automatically fix js files
   Requires: dash-2.13.0
   Homepage: https://github.com/aaronjensen/eslintd-fix
Other versions: 20171124.1735 (installed), 20171125.1432 (melpa).
```
When I run `eslintd-fix` interactive function, I see `eslintd-finx Starting eslint_d` but it does not work and does not run eslint_d on save.

**Comment by aaronjensen** [comment]
@psamim Ok, those seem like the most recent versions. 

Can you eval these with `M-:` in a js buffer and send any messages they send as well as the return value:

`(executable-find eslintd-fix-executable)`

`(eslintd-fix--verify (executable-find eslintd-fix-executable))`

`(eslintd-fix--start)`

**Comment by aaronjensen** [comment]
@psamim Also, can you please try #9 

If you're using spacemacs, you can use: 

```lisp
    (eslintd-fix :location (recipe :fetcher github :repo "aaronjensen/eslintd-fix" :branch "improve-verification-and-startup"))
```

Instead of `esilntd-fix` in `dotspacemacs-additional-packages`

**Comment by aaronjensen** [comment]
@psamim @zphr  I was able to reproduce this on a colleague's machine. I just pushed a fix to master, please give it a shot after it. It should be on melpa in 6 hours or so.

If you don't want to wait, try to eval:

```lisp
(defun eslintd-fix--open-connection ()
  "Open a connection to eslint_d.

Return nil if eslint_d is not running. Also close the existing,
cached connection if it is already open."
  (and eslintd-fix-connection
       (delete-process eslintd-fix-connection))
  (-when-let* ((portfile (or (eslintd-fix--read-portfile)
                             (and (eslintd-fix--start)
                                  (eslintd-fix--read-portfile))))
               (port (car portfile))
               (token (cadr portfile))
               (connection
                (open-network-stream "eslintd-fix" nil "127.0.0.1" port :nowait t)))
    (process-put connection 'eslintd-fix-token token)
    (set-process-query-on-exit-flag connection nil)
    (set-process-sentinel connection 'eslintd-fix--connection-sentinel)
    (setq eslintd-fix-connection connection)))
```

then give it a shot. Thanks!

**Comment by psamim** [comment]
Yes! It seems fixed now. Thank you for this great and useful package.

**Comment by aaronjensen** [comment]
That's great, thank you for confirming and you're welcome.

**Comment by zphr** [comment]
Can confirm everything works again! Thanks!
